# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalconstants

class TestLoginAndShopping():
  def setup_method(self, method):
     self.driver = webdriver.Chrome()
     self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def WaitForElementVisible(self,locator,timeout=5):
    WebDriverWait(self.driver,timeout).until(ec.visibility_of_element_located(locator))
  
  def test_loginAndShopping(self):
    self.driver.get(globalconstants.URL)
    self.driver.set_window_size(802, 920)
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"username\"]"))
    usernameInput = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]")
    usernameInput.send_keys("standard_user")
    
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"password\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"login-button\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]").click()
    self.WaitForElementVisible((By.LINK_TEXT, "2"))
    self.driver.find_element(By.LINK_TEXT, "2").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"checkout\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"firstName\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("Yunus")
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"lastName\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("Basak")
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"postalCode\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("34000")
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"continue\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"finish\"]"))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
    self.WaitForElementVisible((By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]"))
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").text == "Back Home"
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
    self.driver.close()
  
